#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-directory-ldap-api
Version  : 1.0.0.m20
Release  : 2
URL      : https://github.com/apache/directory-ldap-api/archive/1.0.0-M20.tar.gz
Source0  : https://github.com/apache/directory-ldap-api/archive/1.0.0-M20.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.jar
Source2  : https://repo1.maven.org/maven2/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.pom
Source3  : https://repo1.maven.org/maven2/org/apache/directory/api/api-asn1-api/1.0.0-M33/api-asn1-api-1.0.0-M33.jar
Source4  : https://repo1.maven.org/maven2/org/apache/directory/api/api-asn1-api/1.0.0-M33/api-asn1-api-1.0.0-M33.pom
Source5  : https://repo1.maven.org/maven2/org/apache/directory/api/api-asn1-ber/1.0.0-M33/api-asn1-ber-1.0.0-M33.jar
Source6  : https://repo1.maven.org/maven2/org/apache/directory/api/api-asn1-ber/1.0.0-M33/api-asn1-ber-1.0.0-M33.pom
Source7  : https://repo1.maven.org/maven2/org/apache/directory/api/api-asn1-parent/1.0.0-M20/api-asn1-parent-1.0.0-M20.pom
Source8  : https://repo1.maven.org/maven2/org/apache/directory/api/api-asn1-parent/1.0.0-M33/api-asn1-parent-1.0.0-M33.pom
Source9  : https://repo1.maven.org/maven2/org/apache/directory/api/api-dsml-engine/1.0.0-M33/api-dsml-engine-1.0.0-M33.jar
Source10  : https://repo1.maven.org/maven2/org/apache/directory/api/api-dsml-engine/1.0.0-M33/api-dsml-engine-1.0.0-M33.pom
Source11  : https://repo1.maven.org/maven2/org/apache/directory/api/api-dsml-parent/1.0.0-M33/api-dsml-parent-1.0.0-M33.pom
Source12  : https://repo1.maven.org/maven2/org/apache/directory/api/api-dsml-parser/1.0.0-M33/api-dsml-parser-1.0.0-M33.jar
Source13  : https://repo1.maven.org/maven2/org/apache/directory/api/api-dsml-parser/1.0.0-M33/api-dsml-parser-1.0.0-M33.pom
Source14  : https://repo1.maven.org/maven2/org/apache/directory/api/api-i18n/1.0.0-M33/api-i18n-1.0.0-M33.jar
Source15  : https://repo1.maven.org/maven2/org/apache/directory/api/api-i18n/1.0.0-M33/api-i18n-1.0.0-M33.pom
Source16  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-client-api/1.0.0-M33/api-ldap-client-api-1.0.0-M33.jar
Source17  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-client-api/1.0.0-M33/api-ldap-client-api-1.0.0-M33.pom
Source18  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-client-parent/1.0.0-M33/api-ldap-client-parent-1.0.0-M33.pom
Source19  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-codec-core/1.0.0-M33/api-ldap-codec-core-1.0.0-M33.jar
Source20  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-codec-core/1.0.0-M33/api-ldap-codec-core-1.0.0-M33.pom
Source21  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-codec-parent/1.0.0-M33/api-ldap-codec-parent-1.0.0-M33.pom
Source22  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-codec-standalone/1.0.0-M33/api-ldap-codec-standalone-1.0.0-M33.jar
Source23  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-codec-standalone/1.0.0-M33/api-ldap-codec-standalone-1.0.0-M33.pom
Source24  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-aci/1.0.0-M33/api-ldap-extras-aci-1.0.0-M33.jar
Source25  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-aci/1.0.0-M33/api-ldap-extras-aci-1.0.0-M33.pom
Source26  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-codec-api/1.0.0-M33/api-ldap-extras-codec-api-1.0.0-M33.jar
Source27  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-codec-api/1.0.0-M33/api-ldap-extras-codec-api-1.0.0-M33.pom
Source28  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-codec/1.0.0-M33/api-ldap-extras-codec-1.0.0-M33.jar
Source29  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-codec/1.0.0-M33/api-ldap-extras-codec-1.0.0-M33.pom
Source30  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-parent/1.0.0-M33/api-ldap-extras-parent-1.0.0-M33.pom
Source31  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-sp/1.0.0-M33/api-ldap-extras-sp-1.0.0-M33.jar
Source32  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-sp/1.0.0-M33/api-ldap-extras-sp-1.0.0-M33.pom
Source33  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-trigger/1.0.0-M33/api-ldap-extras-trigger-1.0.0-M33.jar
Source34  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-trigger/1.0.0-M33/api-ldap-extras-trigger-1.0.0-M33.pom
Source35  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-util/1.0.0-M33/api-ldap-extras-util-1.0.0-M33.jar
Source36  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-extras-util/1.0.0-M33/api-ldap-extras-util-1.0.0-M33.pom
Source37  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-model/1.0.0-M33/api-ldap-model-1.0.0-M33.jar
Source38  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-model/1.0.0-M33/api-ldap-model-1.0.0-M33.pom
Source39  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-net-mina/1.0.0-M33/api-ldap-net-mina-1.0.0-M33.jar
Source40  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-net-mina/1.0.0-M33/api-ldap-net-mina-1.0.0-M33.pom
Source41  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-net-parent/1.0.0-M33/api-ldap-net-parent-1.0.0-M33.pom
Source42  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-parent/1.0.0-M33/api-ldap-parent-1.0.0-M33.pom
Source43  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-schema-data/1.0.0-M33/api-ldap-schema-data-1.0.0-M33.jar
Source44  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-schema-data/1.0.0-M33/api-ldap-schema-data-1.0.0-M33.pom
Source45  : https://repo1.maven.org/maven2/org/apache/directory/api/api-ldap-schema-parent/1.0.0-M33/api-ldap-schema-parent-1.0.0-M33.pom
Source46  : https://repo1.maven.org/maven2/org/apache/directory/api/api-parent/1.0.0-M20/api-parent-1.0.0-M20.pom
Source47  : https://repo1.maven.org/maven2/org/apache/directory/api/api-parent/1.0.0-M33/api-parent-1.0.0-M33.pom
Source48  : https://repo1.maven.org/maven2/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.jar
Source49  : https://repo1.maven.org/maven2/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.pom
Source50  : https://repo1.maven.org/maven2/org/apache/directory/api/api-util/1.0.0-M33/api-util-1.0.0-M33.jar
Source51  : https://repo1.maven.org/maven2/org/apache/directory/api/api-util/1.0.0-M33/api-util-1.0.0-M33.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : ANTLR-PD Apache-2.0
Requires: mvn-directory-ldap-api-data = %{version}-%{release}

%description
This distribution includes cryptographic software.  The country in
which you currently reside may have restrictions on the import,
possession, use, and/or re-export to another country, of
encryption software.  BEFORE using any encryption software, please
check your country's laws, regulations and policies concerning the
import, possession, or use, and re-export of encryption software, to
see if this is permitted.  See <http://www.wassenaar.org/> for more
information.

%package data
Summary: data components for the mvn-directory-ldap-api package.
Group: Data

%description data
data components for the mvn-directory-ldap-api package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M20
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M20
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M33
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M33/api-asn1-api-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M33
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M33/api-asn1-api-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-ber/1.0.0-M33
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-ber/1.0.0-M33/api-asn1-ber-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-ber/1.0.0-M33
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-ber/1.0.0-M33/api-asn1-ber-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-parent/1.0.0-M20
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-parent/1.0.0-M20/api-asn1-parent-1.0.0-M20.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-parent/1.0.0-M33
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-parent/1.0.0-M33/api-asn1-parent-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-engine/1.0.0-M33
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-engine/1.0.0-M33/api-dsml-engine-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-engine/1.0.0-M33
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-engine/1.0.0-M33/api-dsml-engine-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-parent/1.0.0-M33
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-parent/1.0.0-M33/api-dsml-parent-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-parser/1.0.0-M33
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-parser/1.0.0-M33/api-dsml-parser-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-parser/1.0.0-M33
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-parser/1.0.0-M33/api-dsml-parser-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-i18n/1.0.0-M33
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-i18n/1.0.0-M33/api-i18n-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-i18n/1.0.0-M33
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-i18n/1.0.0-M33/api-i18n-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-client-api/1.0.0-M33
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-client-api/1.0.0-M33/api-ldap-client-api-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-client-api/1.0.0-M33
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-client-api/1.0.0-M33/api-ldap-client-api-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-client-parent/1.0.0-M33
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-client-parent/1.0.0-M33/api-ldap-client-parent-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-core/1.0.0-M33
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-core/1.0.0-M33/api-ldap-codec-core-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-core/1.0.0-M33
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-core/1.0.0-M33/api-ldap-codec-core-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-parent/1.0.0-M33
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-parent/1.0.0-M33/api-ldap-codec-parent-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-standalone/1.0.0-M33
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-standalone/1.0.0-M33/api-ldap-codec-standalone-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-standalone/1.0.0-M33
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-standalone/1.0.0-M33/api-ldap-codec-standalone-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-aci/1.0.0-M33
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-aci/1.0.0-M33/api-ldap-extras-aci-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-aci/1.0.0-M33
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-aci/1.0.0-M33/api-ldap-extras-aci-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-codec-api/1.0.0-M33
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-codec-api/1.0.0-M33/api-ldap-extras-codec-api-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-codec-api/1.0.0-M33
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-codec-api/1.0.0-M33/api-ldap-extras-codec-api-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-codec/1.0.0-M33
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-codec/1.0.0-M33/api-ldap-extras-codec-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-codec/1.0.0-M33
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-codec/1.0.0-M33/api-ldap-extras-codec-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-parent/1.0.0-M33
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-parent/1.0.0-M33/api-ldap-extras-parent-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-sp/1.0.0-M33
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-sp/1.0.0-M33/api-ldap-extras-sp-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-sp/1.0.0-M33
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-sp/1.0.0-M33/api-ldap-extras-sp-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-trigger/1.0.0-M33
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-trigger/1.0.0-M33/api-ldap-extras-trigger-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-trigger/1.0.0-M33
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-trigger/1.0.0-M33/api-ldap-extras-trigger-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-util/1.0.0-M33
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-util/1.0.0-M33/api-ldap-extras-util-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-util/1.0.0-M33
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-util/1.0.0-M33/api-ldap-extras-util-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-model/1.0.0-M33
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-model/1.0.0-M33/api-ldap-model-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-model/1.0.0-M33
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-model/1.0.0-M33/api-ldap-model-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-net-mina/1.0.0-M33
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-net-mina/1.0.0-M33/api-ldap-net-mina-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-net-mina/1.0.0-M33
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-net-mina/1.0.0-M33/api-ldap-net-mina-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-net-parent/1.0.0-M33
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-net-parent/1.0.0-M33/api-ldap-net-parent-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-parent/1.0.0-M33
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-parent/1.0.0-M33/api-ldap-parent-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-schema-data/1.0.0-M33
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-schema-data/1.0.0-M33/api-ldap-schema-data-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-schema-data/1.0.0-M33
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-schema-data/1.0.0-M33/api-ldap-schema-data-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-schema-parent/1.0.0-M33
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-schema-parent/1.0.0-M33/api-ldap-schema-parent-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-parent/1.0.0-M20
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-parent/1.0.0-M20/api-parent-1.0.0-M20.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-parent/1.0.0-M33
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-parent/1.0.0-M33/api-parent-1.0.0-M33.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-util/1.0.0-M20
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-util/1.0.0-M20
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-util/1.0.0-M33
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-util/1.0.0-M33/api-util-1.0.0-M33.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-util/1.0.0-M33
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/org/apache/directory/api/api-util/1.0.0-M33/api-util-1.0.0-M33.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M33/api-asn1-api-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M33/api-asn1-api-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-ber/1.0.0-M33/api-asn1-ber-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-ber/1.0.0-M33/api-asn1-ber-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-parent/1.0.0-M20/api-asn1-parent-1.0.0-M20.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-asn1-parent/1.0.0-M33/api-asn1-parent-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-engine/1.0.0-M33/api-dsml-engine-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-engine/1.0.0-M33/api-dsml-engine-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-parent/1.0.0-M33/api-dsml-parent-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-parser/1.0.0-M33/api-dsml-parser-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-dsml-parser/1.0.0-M33/api-dsml-parser-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-i18n/1.0.0-M33/api-i18n-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-i18n/1.0.0-M33/api-i18n-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-client-api/1.0.0-M33/api-ldap-client-api-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-client-api/1.0.0-M33/api-ldap-client-api-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-client-parent/1.0.0-M33/api-ldap-client-parent-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-core/1.0.0-M33/api-ldap-codec-core-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-core/1.0.0-M33/api-ldap-codec-core-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-parent/1.0.0-M33/api-ldap-codec-parent-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-standalone/1.0.0-M33/api-ldap-codec-standalone-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-codec-standalone/1.0.0-M33/api-ldap-codec-standalone-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-aci/1.0.0-M33/api-ldap-extras-aci-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-aci/1.0.0-M33/api-ldap-extras-aci-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-codec-api/1.0.0-M33/api-ldap-extras-codec-api-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-codec-api/1.0.0-M33/api-ldap-extras-codec-api-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-codec/1.0.0-M33/api-ldap-extras-codec-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-codec/1.0.0-M33/api-ldap-extras-codec-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-parent/1.0.0-M33/api-ldap-extras-parent-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-sp/1.0.0-M33/api-ldap-extras-sp-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-sp/1.0.0-M33/api-ldap-extras-sp-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-trigger/1.0.0-M33/api-ldap-extras-trigger-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-trigger/1.0.0-M33/api-ldap-extras-trigger-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-util/1.0.0-M33/api-ldap-extras-util-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-extras-util/1.0.0-M33/api-ldap-extras-util-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-model/1.0.0-M33/api-ldap-model-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-model/1.0.0-M33/api-ldap-model-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-net-mina/1.0.0-M33/api-ldap-net-mina-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-net-mina/1.0.0-M33/api-ldap-net-mina-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-net-parent/1.0.0-M33/api-ldap-net-parent-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-parent/1.0.0-M33/api-ldap-parent-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-schema-data/1.0.0-M33/api-ldap-schema-data-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-schema-data/1.0.0-M33/api-ldap-schema-data-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-ldap-schema-parent/1.0.0-M33/api-ldap-schema-parent-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-parent/1.0.0-M20/api-parent-1.0.0-M20.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-parent/1.0.0-M33/api-parent-1.0.0-M33.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.pom
/usr/share/java/.m2/repository/org/apache/directory/api/api-util/1.0.0-M33/api-util-1.0.0-M33.jar
/usr/share/java/.m2/repository/org/apache/directory/api/api-util/1.0.0-M33/api-util-1.0.0-M33.pom
